###########START
print('Enter an adjective:')
adjective1 = input()
print('Enter an adjective:')
adjective2 = input()
print('Enter a type of bird')
type_of_bird = input()
print('Enter a room in a house')
room_in_a_house = input()
print('Enter a verb (past tense)')
verb_past_tense = input()
print('Enter a verb')
verb = input()
print('Enter a relatives name')
relatives_name = input()
print('Enter a noun')
noun1 = input()
print('Enter a liquid')
liquid = input()
print('Enter a verb ending in -ing')
verb_ending_in_ing1 = input()
print('Enter a part of the body(plural) ')
part_of_the_body_plural = input()
print('Enter a plural noun')
plural_noun = input()
print('Enter a verb ending in -ing')
verb_ending_in_ing2 = input()
print('Enter a noun')
noun2 = input()

print('It was a ' + adjective1 + ', cold November day. I')
print('woke up to the' + adjective2 + 'smell of' + type_of_bird)
print('roasting in the' + room_in_a_house +' downstairs. I')
print(verb_past_tense + 'down the stairs to see if I could')
print('help' + verb + 'the dinner. My mom said,')
print('see if' + relatives_name + 'needs a fresh' + noun1 + '." So I')
print('carried a tray of glasses full of' + liquid + 'into')
print('the' + verb_ending_in_ing1 + 'room. When I got there,I')
print('couldnt belive my' + part_of_the_body_plural + 'There were' )
print(plural_noun + verb_ending_in_ing2 + 'on the' + noun2 + '!')
